spring:
  application:
    name: Eureka

server:
  port: 8702

eureka:
  server:
    enable-self-preservation: false
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka1:8701/eureka