spring:
  application:
    name: Eureka

server:
  port: 8702

eureka:
  server:
    enable-self-preservation: false
    response-cache-update-interval-ms: 4000
  instance:
    # С какой периодичностью обновлять инф о сервисе
    leaseRenewalIntervalInSeconds: 10

    # С какой периодич вычищать мертвые сервисы
    leaseExpirationDurationInSeconds: 30
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8701/eureka
    initialInstanceInfoReplicationIntervalSeconds: 11